---
- hosts: all
  tasks:
    - name: Backup All Database
      shell: docker exec MariaDB mysqldump --all-databases --single-transaction --quick --lock-tables=false > full-backup-$(date +%F).sql -u root --password=admin123
    
    - name: Delete Backups Older than a week
      shell: find ~/ -type f -name 'full-backup-*' -mtime +7 -exec rm {} \;
