---
- hosts: all
  become: yes
  become_method: sudo
  name: Update Cache
  tasks:
  - name: Run apt-get update
    apt:
      update_cache: yes
    ignore_errors: yes
    when: ansible_distribution=="Ubuntu"
